### ISSUE TITLE
Did we ever upload a video demonstrating the magical capabilities of this software? 

### ISSUE THREAD

**Issue by TheTeraByte** [aznhassan/speedster#35]

**Comment by aznhassan** [comment]
I don't believe we did. I'll make the repo public & rumage around foi the
video.

**Comment by nighttime** [comment]
Funny—I was just thinking about making a GIF for it.

**Comment by aznhassan** [comment]
The video is a bit long, but I feel it belongs on the github page. Let your
feelings be known if you disagree.

**Comment by aznhassan** [comment]
Repo was already public and we already uploaded the file, it's called tutorial.webm
